<?php
/*
cPanel Backup Script
Generated by https://www.ericzhang.me/projects/cpanel-auto-backup/
*/

$auth = base64_encode("jxlcvuub:tamezuqa");
$domain = "http://62.138.138.19:2082/";
$theme = "paper_lantern";
$ftp = false;
$ftp_server = "85.52.35.163";
$ftp_username = "backupcyc";
$ftp_password = "El_C0dig0";
$ftp_port = "35452";
$ftp_directory = "/";

// Do not change below
$url = $domain . "/frontend/" . $theme . "/backup/dofullbackup.html";
$data = array();
if ($ftp) {
  $data["dest"] = "ftp";
  $data["server"] = $ftp_server;
  $data["user"] = $ftp_username;
  $data["pass"] = $ftp_password;
  $data["port"] = $ftp_port;
  $data["rdir"] = $ftp_directory;
}

$options = array(
  'http' => array(
    'header'  => "Content-type: application/x-www-form-urlencoded\r\nAuthorization: Basic $auth\r\n",
    'method'  => 'POST',
    'content' => http_build_query($data)
  ),
  'ssl' => array(
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true
  )
);

$context = stream_context_create($options);
$result = file_get_contents($url, false, $context);
if ($result === FALSE) {
  exit("Error backing up server.");
}

echo $result;
?>
